name: Update Kanban Status

on:
  issues:
    types:
      - assigned

jobs:
  update-kanban-status:
    runs-on: ubuntu-latest

    steps:
    - name: Check if issue is assigned
      id: check-assignee
      run: echo "::set-output name=assignee::${{ github.event.issue.assignee }}"

    - name: Update Kanban Status
      if: steps.check-assignee.outputs.assignee != null
      run: |
        ISSUE_NUMBER="${{ github.event.issue.number }}"
        PROJECT_COLUMN_ID="Todo"

        API_URL="https://api.github.com/projects/columns/${PROJECT_COLUMN_ID}/moves"
        HEADERS="Authorization: Bearer ${{ secrets.ACTION_TOKEN }}"
        DATA="{\"position\":\"top\",\"content_id\":$ISSUE_NUMBER,\"content_type\":\"Issue\"}"

        curl -X POST -H "$HEADERS" -d "$DATA" "$API_URL"
