name: Update Kanban Status

on:
  issues:
    types:
      - assigned

jobs:
  update_kanban_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue is assigned
        run: echo "Checking if issue is assigned..."

      - name: Update Kanban Status
        env:
          GH_PAT: ${{ secrets.ACTION_TOKEN }}
        run: |
          ISSUE_NUMBER=$(jq -r .issue.number "$GITHUB_EVENT_PATH")
          STATUS_UPDATE="{\"note\":\"Issue assigned to ${{ github.event.issue.assignee.login }}\"}"
          curl -X POST \
              -H "Authorization: token $GH_PAT" \
              -H "Accept: application/vnd.github.inertia-preview+json" \
              -d "$STATUS_UPDATE" \
              "https://api.github.com/projects/columns/Todo/cards/$ISSUE_NUMBER/notes"
