name: Auto Kanban Board
on:
  issues:
    types:
      - assigned

jobs:
  automate-kanban-board:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project and Column ID
        id: get-project-and-column-id
        run: |
          github_token="${{ secrets.ACTION_TOKEN }}"
          project_name="@1eecan's untitled project"
          column_name="Todo"

          # GitHub API를 사용하여 리포지토리의 프로젝트 목록 가져오기
          projects=$(curl -s -X GET \
            -H "Authorization: token $github_token" \
            "https://api.github.com/repos/${{ github.repository }}/projects")

          for row in $(echo "$projects" | jq -c '.[]'); do
            name=$(echo "$row" | jq -r '.name')
            id=$(echo "$row" | jq -r '.id')
            if [ "$name" == "$project_name" ]; then
              project_id="$id"
              echo "Found project ID: $project_id"
            fi
          done

          if [ -z "$project_id" ]; then
            echo "Project not found."
            exit 1
          fi

          # GitHub API를 사용하여 프로젝트의 컬럼 목록 가져오기
          columns=$(curl -s -X GET \
            -H "Authorization: token $github_token" \
            "https://api.github.com/projects/$project_id/columns")

          for row in $(echo "$columns" | jq -c '.[]'); do
            name=$(echo "$row" | jq -r '.name')
            id=$(echo "$row" | jq -r '.id')
            if [ "$name" == "$column_name" ]; then
              column_id="$id"
              echo "Found column ID: $column_id"
            fi
          done

          if [ -z "$column_id" ]; then
            echo "Column not found."
            exit 1
          fi

          echo "::set-output name=project_id::$project_id"
          echo "::set-output name=column_id::$column_id"
        env:
          PROJECT_NAME: $project_name
